#!/bin/bash
# Auto-generated by submit_hpc.sh — do not edit.
set -euo pipefail
CONDA_ENV="prompt-pipeline"
REPO_ROOT="${SLURM_SUBMIT_DIR:?}"
cd "$REPO_ROOT"
source ~/.bashrc
conda activate "$CONDA_ENV"
set -a; [[ -f "${REPO_ROOT}/.env" ]] && source "${REPO_ROOT}/.env"; set +a
export OMP_NUM_THREADS=8 PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
export LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONIOENCODING=utf-8

BACKBONE="${BACKBONE:-sd21}"
if [[ "$BACKBONE" == "sdxl" ]]; then
    OVERRIDE=(--config t2i.backbone=sdxl
              t2i.model_id=stabilityai/stable-diffusion-xl-base-1.0
              t2i.resolution=1024 t2i.prediction_type=epsilon)
else
    OVERRIDE=(--config t2i.backbone=sd21
              t2i.model_id=sd2-community/stable-diffusion-2-1
              t2i.resolution=768 t2i.prediction_type=v_prediction)
fi

echo "========================================"
echo "Job      : $SLURM_JOB_ID"
echo "Node     : $(hostname)"
echo "Backbone : $BACKBONE"
echo "Phase    : diagnostics (cfg_stability, llada_trajectory, trajectory)"
echo "========================================"
nvidia-smi

[[ -n "${WANDB_API_KEY:-}" ]] && \
    python -c "import wandb; wandb.login(key='${WANDB_API_KEY}', relogin=True)" 2>/dev/null || true

# Start Ollama for llada_trajectory --track-content (scene-graph per step).
# If it can't start, the diagnostic still runs without content tracking.
OLLAMA_BIN="${OLLAMA_BIN:-$HOME/ollama-dist/bin/ollama}"
OLLAMA_PID=""
if [[ -x "$OLLAMA_BIN" ]]; then
    "$OLLAMA_BIN" serve & OLLAMA_PID=$!
    for i in $(seq 1 20); do
        curl -sf http://localhost:11434/api/tags >/dev/null 2>&1 && break
        sleep 2
    done
    echo "Ollama started (PID $OLLAMA_PID)."
else
    echo "WARN: Ollama not found — llada_trajectory will run without content tracking."
fi

# 1. CFG-stability (image-layer trajectory + multi-CFG line graphs)
echo ""; echo "--- cfg_stability ---"
python experiments/cfg_stability.py --n-prompts 8 --set color_binding \
    "${OVERRIDE[@]}" || echo "WARN: cfg_stability failed (non-fatal)."

# 2. LLaDA language-layer trajectory (unmasking schedule + content emerging)
echo ""; echo "--- llada_trajectory ---"
if [[ -n "$OLLAMA_PID" ]]; then
    python experiments/llada_trajectory.py --n-prompts 8 --set rq5_compositional \
        --track-content "${OVERRIDE[@]}" || echo "WARN: llada_trajectory failed (non-fatal)."
else
    python experiments/llada_trajectory.py --n-prompts 10 --set rq5_compositional \
        "${OVERRIDE[@]}" || echo "WARN: llada_trajectory failed (non-fatal)."
fi

# 3. Single-CFG denoising trajectory
echo ""; echo "--- trajectory ---"
python experiments/trajectory.py --n-prompts 8 \
    "${OVERRIDE[@]}" || echo "WARN: trajectory failed (non-fatal)."

[[ -n "$OLLAMA_PID" ]] && kill "$OLLAMA_PID" 2>/dev/null || true

# Regenerate plots so the new diagnostic figures render.
echo ""; echo "--- Regenerating plots (outputs/${BACKBONE}) ---"
python -m evaluation.plotting "outputs/${BACKBONE}" || echo "WARN: plotting failed (non-fatal)."
echo "Diagnostics complete for $BACKBONE."
