#!/bin/bash
# Auto-generated by submit_hpc.sh — do not edit.
# Warm the AR rewrite cache: Ollama + Llama 3.1 over all experiment prompts.
# GPU node so Ollama can offload llama3.1 layers to VRAM (~4 GB).
set -euo pipefail
CONDA_ENV="prompt-pipeline"

# sbatch copies this script to the slurmd spool dir — use SLURM_SUBMIT_DIR.
REPO_ROOT="${SLURM_SUBMIT_DIR:?SLURM_SUBMIT_DIR not set — submit via sbatch from repo root}"
cd "$REPO_ROOT"

source ~/.bashrc
conda activate "$CONDA_ENV"

set -a; [[ -f "${REPO_ROOT}/.env" ]] && source "${REPO_ROOT}/.env"; set +a

# ------------------------------
# Locate Ollama.
# Primary: official tarball install at ~/ollama-dist (bin/ + lib/ollama/).
# NOTE: conda-forge/homebrew ollama packages are BROKEN for GGUF models —
# they omit the llama-server runner, which ollama looks up via hardcoded
# paths relative to its own binary. The tarball ships the full layout:
#   mkdir -p ~/ollama-dist
#   curl -L https://ollama.com/download/ollama-linux-amd64.tgz | tar -xz -C ~/ollama-dist
# OLLAMA_BIN in .env overrides everything.
# ------------------------------
if [[ -z "${OLLAMA_BIN:-}" ]]; then
    for candidate in \
        "$HOME/ollama-dist/bin/ollama" \
        "$HOME/bin/ollama" \
        "$HOME/.local/bin/ollama" \
        "$(command -v ollama 2>/dev/null || true)"; do
        if [[ -n "$candidate" && -x "$candidate" ]]; then
            OLLAMA_BIN="$candidate"
            break
        fi
    done
fi
if [[ -z "${OLLAMA_BIN:-}" || ! -x "${OLLAMA_BIN}" ]]; then
    echo "FATAL: ollama binary not found on $(hostname)." >&2
    echo "Install the official tarball (includes llama-server runner):" >&2
    echo "  mkdir -p ~/ollama-dist" >&2
    echo "  curl -L https://ollama.com/download/ollama-linux-amd64.tgz | tar -xz -C ~/ollama-dist" >&2
    exit 1
fi

# Verify the install is complete — catches broken conda/brew-style installs early.
# Two valid layouts:
#   - Ollama >= 0.2x: separate llama-server runner in lib/ollama/
#   - Ollama 0.1x (e.g. v0.13.5): integrated runner, ggml backends in lib/ollama/
# Broken packages ship the bare binary with NO lib/ollama contents at all.
OLLAMA_LIB_DIR="$(dirname "$OLLAMA_BIN")/../lib/ollama"
if [[ ! -e "$OLLAMA_LIB_DIR/llama-server" \
   && ! -e "$(dirname "$OLLAMA_BIN")/llama-server" \
   && -z "$(ls "$OLLAMA_LIB_DIR"/libggml-base.so* 2>/dev/null)" ]]; then
    echo "FATAL: $OLLAMA_BIN exists but no inference runtime found (no llama-server, no ggml libs)." >&2
    echo "This install cannot run GGUF models. Use the official bundle:" >&2
    echo "  curl -L https://github.com/ollama/ollama/releases/download/v0.13.5/ollama-linux-amd64.tgz | tar -xz -C ~/ollama-dist" >&2
    exit 1
fi
echo "Using Ollama: $OLLAMA_BIN ($("$OLLAMA_BIN" --version 2>/dev/null || echo 'version unknown'))"

# Model weights live on the shared home filesystem — visible to all nodes.
export OLLAMA_MODELS="${OLLAMA_MODELS:-$HOME/.ollama/models}"

# ------------------------------
# CUDA / PyTorch config
# ------------------------------
export OMP_NUM_THREADS=8
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
export PYTHONFAULTHANDLER=1

echo "========================================"
echo "Job      : $SLURM_JOB_ID"
echo "Node     : $(hostname)"
echo "GPUs     : ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "Phase    : AR rewrite cache warmup (ar_clip)"
echo "========================================"
nvidia-smi

# Start Ollama in the background and wait for it to be ready.
"$OLLAMA_BIN" serve &
OLLAMA_PID=$!
echo "Ollama PID: $OLLAMA_PID"

# Poll until /api/tags responds (up to 60 s) — FAIL HARD on timeout.
OLLAMA_READY=false
for i in $(seq 1 30); do
    if curl -sf http://localhost:11434/api/tags > /dev/null 2>&1; then
        OLLAMA_READY=true
        break
    fi
    # Bail out early if the server process already died
    if ! kill -0 "$OLLAMA_PID" 2>/dev/null; then
        echo "FATAL: Ollama process died during startup." >&2
        exit 1
    fi
    sleep 2
done
if ! $OLLAMA_READY; then
    echo "FATAL: Ollama did not become ready within 60 s." >&2
    kill "$OLLAMA_PID" 2>/dev/null || true
    exit 1
fi
echo "Ollama ready."

# Verify the model is actually pulled — fail with a clear message, not a
# cryptic 404 from the rewriter mid-run.
OLLAMA_MODEL="${OLLAMA_MODEL:-llama3.1}"
if ! curl -sf http://localhost:11434/api/tags | grep -q "\"${OLLAMA_MODEL}"; then
    echo "FATAL: model '${OLLAMA_MODEL}' not found in Ollama." >&2
    echo "Pull it once from a login node:" >&2
    echo "  conda activate ${CONDA_ENV} && ollama serve & ollama pull ${OLLAMA_MODEL}" >&2
    kill "$OLLAMA_PID" 2>/dev/null || true
    exit 1
fi
echo "Model '${OLLAMA_MODEL}' available."

python experiments/run_experiment.py \
    --rq 0 \
    --pipeline ar_clip \
    --no-wandb

echo "AR warmup complete."
kill "$OLLAMA_PID" 2>/dev/null || true
