#!/bin/bash
# Auto-generated by submit_hpc.sh — do not edit.
set -euo pipefail
CONDA_ENV="prompt-pipeline"

# sbatch copies this script to the slurmd spool dir, so BASH_SOURCE cannot be
# used to locate the repo. SLURM_SUBMIT_DIR = directory sbatch was invoked
# from, which submit_hpc.sh guarantees is the repo root.
REPO_ROOT="${SLURM_SUBMIT_DIR:?SLURM_SUBMIT_DIR not set — submit via sbatch from repo root}"
cd "$REPO_ROOT"

source ~/.bashrc
conda activate "$CONDA_ENV"

set -a; [[ -f "${REPO_ROOT}/.env" ]] && source "${REPO_ROOT}/.env"; set +a

# ------------------------------
# CUDA / PyTorch config
# ------------------------------
export OMP_NUM_THREADS=8
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
export PYTHONFAULTHANDLER=1

echo "========================================"
echo "Job      : $SLURM_JOB_ID"
echo "Node     : $(hostname)"
echo "Repo     : $REPO_ROOT"
echo "GPUs     : ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "RQ       : $RQ"
echo "========================================"
nvidia-smi

[[ -n "${WANDB_API_KEY:-}" ]] && \
    python -c "import wandb; wandb.login(key='${WANDB_API_KEY}', relogin=True)" 2>/dev/null || true

# Run all pipelines sequentially in this single job
PIPELINE_NAMES=("raw_clip" "ar_clip" "llada_clip")
for PIPELINE_NAME in "${PIPELINE_NAMES[@]}"; do
    echo ""
    echo "--- Pipeline: $PIPELINE_NAME ---"
    python experiments/run_experiment.py \
        --rq "$RQ" \
        --pipeline "$PIPELINE_NAME" \
        --seed "${SEED:-42}"
done
echo "All pipelines complete for RQ${RQ}."
