#!/bin/bash
# Auto-generated by submit_hpc.sh — do not edit.
# Warm the LLaDA rewrite cache: LLaDA-8B-Instruct over all experiment prompts.
set -euo pipefail
CONDA_ENV="prompt-pipeline"

# sbatch copies this script to the slurmd spool dir — use SLURM_SUBMIT_DIR.
REPO_ROOT="${SLURM_SUBMIT_DIR:?SLURM_SUBMIT_DIR not set — submit via sbatch from repo root}"
cd "$REPO_ROOT"

source ~/.bashrc
conda activate "$CONDA_ENV"

set -a; [[ -f "${REPO_ROOT}/.env" ]] && source "${REPO_ROOT}/.env"; set +a

# ------------------------------
# CUDA / PyTorch config
# ------------------------------
export OMP_NUM_THREADS=8
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
export PYTHONFAULTHANDLER=1

echo "========================================"
echo "Job      : $SLURM_JOB_ID"
echo "Node     : $(hostname)"
echo "GPUs     : ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "Phase    : LLaDA rewrite cache warmup (llada_clip)"
echo "========================================"
nvidia-smi

[[ -n "${WANDB_API_KEY:-}" ]] && \
    python -c "import wandb; wandb.login(key='${WANDB_API_KEY}', relogin=True)" 2>/dev/null || true

python experiments/run_experiment.py \
    --rq 0 \
    --pipeline llada_clip \
    --no-wandb

echo "LLaDA warmup complete."
