#!/usr/bin/env bash
# =============================================================================
# scripts/submit_hpc.sh
#
# Submit all experiment jobs to SLURM.
#
# Parallelisation strategy
# ------------------------
#   Each RQ is submitted as a SLURM array job.  Array task ID maps to one
#   pipeline×encoder combination so all six conditions run simultaneously:
#
#     Task 0  →  raw_clip
#     Task 1  →  raw_longclip
#     Task 2  →  ar_clip
#     Task 3  →  ar_longclip
#     Task 4  →  llada_clip
#     Task 5  →  llada_longclip
#
#   RQ1 (text-only, no image gen) and RQ3 (CFG sweep) additionally aggregate
#   results in a short follow-up job that depends on the array completing.
#
# Usage
# -----
#   bash scripts/submit_hpc.sh              # submit all RQs
#   bash scripts/submit_hpc.sh --rq 2      # submit only RQ2
#   bash scripts/submit_hpc.sh --dry-run   # print sbatch commands, don't submit
#
# Requirements
# ------------
#   - SLURM environment (sbatch, squeue)
#   - source venv/bin/activate or equivalent in your .bashrc / module system
#   - WANDB_API_KEY set in .env or environment
#   - Edit the SLURM resource parameters below to match your cluster
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# Cluster resource settings — edit for your partition and hardware
# ---------------------------------------------------------------------------
PARTITION="gpu"             # SLURM partition name
GPU_TYPE="a100"             # GPU constraint (blank = any GPU)
CPUS_PER_TASK=8
MEM_PER_NODE="64G"
TIME_RQ1="02:00:00"         # RQ1: text-only, fast
TIME_RQ2="12:00:00"         # RQ2: image gen + scoring, slow
TIME_RQ3="06:00:00"         # RQ3: CFG sweep
TIME_RQ4="10:00:00"         # RQ4: AR vs LLaDA
TIME_MERGE="00:30:00"       # Aggregation / merge step

VENV="$REPO_ROOT/venv"
LOG_DIR="$REPO_ROOT/logs/slurm"
mkdir -p "$LOG_DIR"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
SUBMIT_RQS=("1" "2" "3" "4")
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --rq)    SUBMIT_RQS=("$2"); shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Load W&B key from .env
# ---------------------------------------------------------------------------
if [[ -f "$REPO_ROOT/.env" ]]; then
    set -a; source "$REPO_ROOT/.env"; set +a
fi
WANDB_API_KEY="${WANDB_API_KEY:-}"

# ---------------------------------------------------------------------------
# Pipeline array mapping
# Pipeline index → "encoder pipeline_name" pair consumed by --pipeline flag
# ---------------------------------------------------------------------------
PIPELINE_NAMES=(
    "raw_clip"
    "raw_longclip"
    "ar_clip"
    "ar_longclip"
    "llada_clip"
    "llada_longclip"
)
N_PIPELINES=${#PIPELINE_NAMES[@]}   # 6

# ---------------------------------------------------------------------------
# Helper: run or print sbatch command
# ---------------------------------------------------------------------------
sbatch_or_print() {
    if $DRY_RUN; then
        echo "[DRY-RUN] sbatch $*"
    else
        sbatch "$@"
    fi
}

# ---------------------------------------------------------------------------
# Helper: build common SLURM header arguments
# ---------------------------------------------------------------------------
common_args() {
    local rq=$1 time_limit=$2
    local constraint_arg=""
    [[ -n "$GPU_TYPE" ]] && constraint_arg="--constraint=${GPU_TYPE}"
    echo \
        "--partition=${PARTITION}" \
        ${constraint_arg:+"$constraint_arg"} \
        "--gres=gpu:1" \
        "--cpus-per-task=${CPUS_PER_TASK}" \
        "--mem=${MEM_PER_NODE}" \
        "--time=${time_limit}" \
        "--output=${LOG_DIR}/rq${rq}_%A_%a.out" \
        "--error=${LOG_DIR}/rq${rq}_%A_%a.err"
}

# ---------------------------------------------------------------------------
# Write the per-task batch script (shared by all RQs)
# ---------------------------------------------------------------------------
TASK_SCRIPT="$REPO_ROOT/scripts/_slurm_task.sh"
cat > "$TASK_SCRIPT" << 'TASK_EOF'
#!/usr/bin/env bash
# Auto-generated by submit_hpc.sh — do not edit manually.
#SBATCH --job-name=prompt-pipeline

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Activate environment
source "${REPO_ROOT}/venv/bin/activate"

# Load .env (W&B key, offline flag, etc.)
[[ -f "${REPO_ROOT}/.env" ]] && set -a && source "${REPO_ROOT}/.env" && set +a

# Log environment
echo "========================================"
echo "Job      : $SLURM_JOB_ID  (array task $SLURM_ARRAY_TASK_ID)"
echo "Node     : $(hostname)"
echo "GPU      : $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo 'none')"
echo "RQ       : $RQ"
echo "Pipeline : $PIPELINE_NAME"
echo "Seed     : ${SEED:-42}"
echo "W&B      : ${WANDB_PROJECT:-prompt-pipeline}"
echo "========================================"

# W&B login (non-interactive, uses WANDB_API_KEY from env)
if [[ -n "${WANDB_API_KEY:-}" ]]; then
    python -c "import wandb; wandb.login(key='${WANDB_API_KEY}', relogin=True)" 2>/dev/null || true
fi

# Run
python experiments/run_experiment.py \
    --rq "$RQ" \
    --pipeline "$PIPELINE_NAME" \
    --seed "${SEED:-42}" \
    ${WANDB_OFFLINE:+--no-wandb} \
    ${EXTRA_ARGS:-}
TASK_EOF
chmod +x "$TASK_SCRIPT"

# ---------------------------------------------------------------------------
# Also need --pipeline flag in run_experiment.py — add it if missing
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Submit jobs
# ---------------------------------------------------------------------------
declare -A ARRAY_JOB_IDS   # rq -> job_id (for dependency chaining)

for RQ in "${SUBMIT_RQS[@]}"; do
    case "$RQ" in
        1) TIME_LIMIT=$TIME_RQ1 ;;
        2) TIME_LIMIT=$TIME_RQ2 ;;
        3) TIME_LIMIT=$TIME_RQ3 ;;
        4) TIME_LIMIT=$TIME_RQ4 ;;
    esac

    # RQ4 needs LLaDA — same array as RQ2
    # For RQ1 (no image gen) we can use fewer resources
    EXTRA=""
    if [[ "$RQ" == "1" ]]; then
        EXTRA="--gres=gpu:0"   # RQ1 is text-only, no GPU needed for encoding
    fi

    echo ""
    echo "=== Submitting RQ${RQ} array (${N_PIPELINES} tasks) ==="

    JOB_ID=$(sbatch_or_print \
        $(common_args "$RQ" "$TIME_LIMIT") \
        --array="0-$((N_PIPELINES-1))" \
        --job-name="prompt-rq${RQ}" \
        ${EXTRA:+$EXTRA} \
        --export=ALL,RQ="${RQ}",SEED=42,WANDB_PROJECT=prompt-pipeline,WANDB_API_KEY="${WANDB_API_KEY}" \
        --wrap="
            export PIPELINE_NAME=\"\${PIPELINE_NAMES[\$SLURM_ARRAY_TASK_ID]}\"
            PIPELINE_NAMES=(raw_clip raw_longclip ar_clip ar_longclip llada_clip llada_longclip)
            export PIPELINE_NAME=\"\${PIPELINE_NAMES[\$SLURM_ARRAY_TASK_ID]}\"
            bash ${TASK_SCRIPT}
        " 2>&1)

    if ! $DRY_RUN; then
        ARRAY_JOB_IDS[$RQ]=$(echo "$JOB_ID" | grep -oP '\d+')
        echo "  Submitted job ${ARRAY_JOB_IDS[$RQ]} (RQ${RQ})"
    fi
done

# ---------------------------------------------------------------------------
# Print summary
# ---------------------------------------------------------------------------
echo ""
echo "============================================================"
echo "  Submitted RQs: ${SUBMIT_RQS[*]}"
if ! $DRY_RUN; then
    echo ""
    echo "  Monitor with:"
    echo "    squeue -u \$USER"
    echo "    tail -f ${LOG_DIR}/rq2_*.out"
    echo ""
    echo "  W&B dashboard:"
    echo "    https://wandb.ai/\${WANDB_ENTITY:-your-username}/prompt-pipeline"
fi
echo "============================================================"
